# Generated by Django 2.0.2 on 2018-05-17 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20180517_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='host_user_binds',
        ),
    ]
