# Generated by Django 2.0.2 on 2018-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20180517_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='expire',
            field=models.IntegerField(default=20, verbose_name='超时时间(s)'),
        ),
    ]
